// SPDX-License-Identifier: MIT
import { callout, code, table } from "../lib.mjs";

export default {
  path: "testing.html",
  title: "Testing & mock server",
  description: "Shared conformance fixtures, the zero-dependency LWS mock server, and the cross-language interop scenario used to keep six clients in lockstep.",
  body: `
<h1>Testing &amp; mock server</h1>
<p class="lead">Six independent implementations only stay consistent if they are tested against the
same data. The repository has three layers of shared testing: conformance fixtures, a mock LWS
server, and an end-to-end interop scenario.</p>
<div id="toc" class="toc"></div>

<h2 id="fixtures">Conformance fixtures</h2>
<p><code>conformance/fixtures/</code> holds language-neutral JSON test vectors. Every client's unit tests load
them directly, so a parsing bug fixed in one language is caught in all six.</p>
${table(
  ["Fixture", "Covers"],
  [
    ["<code>link-headers.json</code>", "RFC 8288 <code>Link</code> parsing: quoting, commas inside URIs, multiple relation types, relative targets"],
    ["<code>www-authenticate.json</code>", "Challenge parsing including several challenges in one header and <code>token68</code>"],
    ["<code>structured-fields.json</code>", "RFC 8941/9651 dictionaries used by <code>Signature-Input</code>, <code>Signature</code> and <code>Content-Digest</code>"],
    ["<code>json-patch.json</code>", "JSON Pointer escaping and JSON Patch serialisation"],
    ["<code>type-queries.json</code>", "<code>application/lws-query+json</code> construction and client-side validation"],
    ["<code>did-key.json</code>", "did:key derivation, including the official did:key P-256 test vector"],
    ["<code>jwt.json</code>", "Self-signed ES256 and EdDSA credentials that every client must verify"],
    ["<code>webhook/*.json</code>", "13 RFC 9421 signed deliveries: 3 valid and 10 attacks (tampered body, recomputed digest, wrong host, replay, missing components, unauthorised key, storage spoofing, algorithm confusion, …)"],
    ["<code>responses/*.json</code>", "Real-shaped HTTP responses (storage description, paginated container with relative ids, linkset, notifications, access documents, OAuth metadata, problem details) with the expected parsed models"],
  ],
)}
<p>The cryptographic fixtures are generated by a committed script (keys are reused, signatures are
re-randomised):</p>
${code("bash", "node conformance/tools/generate-fixtures.mjs")}

<h2 id="mock-server">Mock LWS server</h2>
<p><code>testing/mock-server</code> is a zero-dependency Node.js (20+) implementation of the server side
of every spec the clients cover. It is an in-memory storage with real authorization (token
exchange, signed access tokens), pagination, linksets, JSON Patch, signed webhooks, access
request and grant containers, and type index and search over HTTP <code>QUERY</code>.</p>
${code("bash", `
node testing/mock-server/server.mjs --port 8787
# LWS mock server listening on http://localhost:8787`)}
${table(
  ["Option", "Default", "Meaning"],
  [
    ["<code>--port &lt;n&gt;</code>", "<code>8787</code>", "Listen port (<code>0</code> picks a free port)"],
    ["<code>--host &lt;addr&gt;</code>", "IPv4 + IPv6 loopback", "Interface to bind"],
    ["<code>--base-url &lt;url&gt;</code>", "<code>http://localhost:&lt;port&gt;</code>", "Public origin used in every URL the server emits"],
    ["<code>--page-size &lt;n&gt;</code>", "<code>5</code>", "Page size for containers, the type index and search results (small, so pagination is always exercised)"],
    ["<code>--no-auth</code>", "off", "Disable authentication; every request acts as <code>anonymous</code>"],
    ["<code>--verbose</code>", "off", "Log requests, token exchanges and webhook deliveries"],
  ],
)}
<p>Node.js 22 or newer is recommended: the server relies on Node's HTTP parser accepting the
<code>QUERY</code> method. It can also be started from code with
<code>startServer({ port: 0 })</code> from <code>testing/mock-server/lib/server.mjs</code>, which
resolves to <code>{ url, close() }</code>.</p>
${table(
  ["URL", "Purpose"],
  [
    ["<code>{base}/</code>", "Storage description (public)"],
    ["<code>{base}/root/</code>", "Storage root container"],
    ["<code>{base}/notifications/</code>", "Notification service (<code>WebhookSubscription</code>)"],
    ["<code>{base}/access/requests/</code>, <code>{base}/access/grants/</code>", "Access request and grant services"],
    ["<code>{base}/types/index</code>, <code>{base}/types/search</code>", "Type index and type search services"],
    ["<code>{base}/.well-known/lws-configuration</code>", "Authorization server metadata (issuer <code>{base}</code>)"],
    ["<code>{base}/oauth/token</code>, <code>{base}/oauth/jwks</code>", "Token exchange endpoint and signing keys"],
  ],
)}
${callout("warn", "Test use only", " The mock server keeps everything in memory, grants every authenticated agent full access and accepts unverified OpenID/SAML tokens in test mode. Never expose it to a network.")}

<h2 id="interop">Interop scenario</h2>
<p><code>conformance/scenario.md</code> defines one end-to-end scenario that every client runs against the mock
server. It covers self-signed did:key authentication through the full 401 → token exchange flow,
discovery, CRUD with conditional requests, JSON Patch, linkset patches, pagination across pages,
type index and search, signed webhook delivery and verification, access requests and grants,
and recursive delete. Each language gates the test on <code>LWS_TEST_SERVER</code>:</p>
${code("bash", `
node testing/mock-server/server.mjs --port 8787 &
export LWS_TEST_SERVER=http://localhost:8787

(cd java && mvn -q verify)
(cd js && npm run test:interop)
(cd cpp && ctest --preset debug)            # or: ctest --test-dir build/mingw-debug
(cd rust && cargo test --test interop)
(cd go && go test -run TestInterop -v .)
(cd python && .venv/bin/pytest tests/test_interop.py)   # Windows: .venv\\Scripts\\pytest`)}

<h2 id="unit">Running each test suite</h2>
<p>Unit tests need no server. See each <a href="contributing.html#building">language's build commands</a>.
Every suite includes in-process HTTP tests that simulate an LWS server, including the
authorization flow, realm-check rejection, three-page pagination, <code>304</code>/<code>412</code>
handling and error mapping.</p>
`,
};
