<!-- SPDX-License-Identifier: MIT -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Ebremer.Lws.Examples</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Ebremer.Lws.Client/Ebremer.Lws.Client.csproj" />
  </ItemGroup>

</Project>
