# SPDX-License-Identifier: MIT
"""lws-client — a client for the W3C Linked Web Storage (LWS) protocol.

Targets the LWS Working Group specifications as of 2026-10-05 (LWS Protocol 1.0 core,
OpenID / SAML / self-signed CID authentication suites, webhook notifications, and the
Search and Type Index services).

Quick start::

    from lws_client import LwsClient

    with LwsClient() as client:
        storage = client.discover_storage("https://storage.example/root/")
        for item in client.list_container(storage.storage_root()):
            print(item.id, item.format)
"""

from __future__ import annotations

from ._util import format_datetime, has_type, parse_datetime
from .access import AccessGrant, AccessPolicy, AccessRequest, AccessTarget, Constraint
from .auth import (
    AccessToken,
    Authenticator,
    AuthorizationServerMetadata,
    BearerTokenAuthenticator,
    CredentialContext,
    CredentialProvider,
    OpenIdCredentials,
    SamlCredentials,
    SelfSignedCredentials,
    TokenExchangeAuthenticator,
    encode_saml_assertion,
    metadata_url,
    parse_token_response_expiry,
    realm_contains,
)
from .client import AsyncLwsClient, AsyncResourceStream, LwsClient, ResourceStream
from .constants import (
    ACCESS_PROFILE,
    ACTIVITYSTREAMS_CONTEXT,
    CID_CONTEXT,
    GRANT_TYPE_TOKEN_EXCHANGE,
    LWS_CONTEXT,
    LWS_NS,
    OPENID_PROVIDER_SERVICE,
    PREFER_LINK_RELATIONS,
    PREFER_SET_LINKSET,
    PUBLIC_AGENT,
    SUBSCRIPTION_WEBHOOK,
    TYPE_ACCESS_GRANT,
    TYPE_ACCESS_POLICY,
    TYPE_ACCESS_REQUEST,
    VERSION,
    WELL_KNOWN_LWS_CONFIGURATION,
    Action,
    ActivityType,
    MediaType,
    Operand,
    Operator,
    Rel,
    ServiceType,
    TokenType,
    Types,
)
from .crypto import (
    SigningKey,
    VerifyingKey,
    controlled_identifier_document,
    decode_jwt_unverified,
    did_key_from_jwk,
    did_key_from_public_key,
    did_key_kid,
    did_key_to_jwk,
    encode_jwt,
    generate_key,
    verify_jwt,
)
from .errors import (
    AuthenticationError,
    BadRequestError,
    ConflictError,
    ForbiddenError,
    GoneError,
    HttpError,
    InsufficientStorageError,
    LwsError,
    MethodNotAllowedError,
    NotAcceptableError,
    NotFoundError,
    NotImplementedByServerError,
    PreconditionFailedError,
    ProblemDetails,
    ProtocolError,
    SignatureVerificationError,
    TransportError,
    UnauthorizedError,
    UnprocessableContentError,
    UnsupportedError,
    UnsupportedMediaTypeError,
)
from .headers import (
    AuthChallenge,
    Link,
    encode_slug,
    parse_link_header,
    parse_www_authenticate,
    serialize_links,
)
from .json_patch import JsonPatch, JsonPointer
from .linkset import LinkContext, Linkset, LinksetDocument, LinkTarget
from .models import (
    Capability,
    ContainedResource,
    ContainerPage,
    CreateResult,
    Resource,
    ResourceMetadata,
    SearchPage,
    Service,
    StorageDescription,
    TypeIndexPage,
    UpdateResult,
    VerificationMethod,
)
from .notifications import (
    Activity,
    ActivityObject,
    Notification,
    Subscription,
    WebhookSubscriptionRequest,
    parse_notification,
)
from .type_index import TypeQuery
from .webhook import (
    AsyncWebhookVerifier,
    VerifiedNotification,
    WebhookVerifier,
    signature_base,
    verify_content_digest,
)

__version__ = VERSION

__all__ = [
    "__version__",
    # clients
    "LwsClient",
    "AsyncLwsClient",
    "ResourceStream",
    "AsyncResourceStream",
    # models
    "ResourceMetadata",
    "Resource",
    "ContainedResource",
    "ContainerPage",
    "SearchPage",
    "TypeIndexPage",
    "CreateResult",
    "UpdateResult",
    "StorageDescription",
    "Service",
    "Capability",
    "VerificationMethod",
    "Linkset",
    "LinkContext",
    "LinkTarget",
    "LinksetDocument",
    "Link",
    "AuthChallenge",
    "ProblemDetails",
    "JsonPatch",
    "JsonPointer",
    "TypeQuery",
    "Notification",
    "Activity",
    "ActivityObject",
    "Subscription",
    "WebhookSubscriptionRequest",
    "AccessRequest",
    "AccessGrant",
    "AccessPolicy",
    "AccessTarget",
    "Constraint",
    # auth
    "Authenticator",
    "BearerTokenAuthenticator",
    "TokenExchangeAuthenticator",
    "AuthorizationServerMetadata",
    "AccessToken",
    "CredentialContext",
    "CredentialProvider",
    "OpenIdCredentials",
    "SamlCredentials",
    "SelfSignedCredentials",
    "encode_saml_assertion",
    "metadata_url",
    "realm_contains",
    "parse_token_response_expiry",
    # crypto
    "SigningKey",
    "VerifyingKey",
    "generate_key",
    "did_key_from_jwk",
    "did_key_from_public_key",
    "did_key_to_jwk",
    "did_key_kid",
    "controlled_identifier_document",
    "encode_jwt",
    "decode_jwt_unverified",
    "verify_jwt",
    # webhooks
    "WebhookVerifier",
    "AsyncWebhookVerifier",
    "VerifiedNotification",
    "signature_base",
    "verify_content_digest",
    # parsers / helpers
    "parse_link_header",
    "serialize_links",
    "parse_www_authenticate",
    "parse_notification",
    "encode_slug",
    "has_type",
    "parse_datetime",
    "format_datetime",
    # errors
    "LwsError",
    "TransportError",
    "HttpError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "MethodNotAllowedError",
    "NotAcceptableError",
    "ConflictError",
    "GoneError",
    "PreconditionFailedError",
    "UnsupportedMediaTypeError",
    "UnprocessableContentError",
    "NotImplementedByServerError",
    "InsufficientStorageError",
    "AuthenticationError",
    "ProtocolError",
    "UnsupportedError",
    "SignatureVerificationError",
    # constants
    "LWS_NS",
    "LWS_CONTEXT",
    "CID_CONTEXT",
    "ACTIVITYSTREAMS_CONTEXT",
    "Rel",
    "Types",
    "MediaType",
    "ServiceType",
    "SUBSCRIPTION_WEBHOOK",
    "TokenType",
    "GRANT_TYPE_TOKEN_EXCHANGE",
    "WELL_KNOWN_LWS_CONFIGURATION",
    "OPENID_PROVIDER_SERVICE",
    "ACCESS_PROFILE",
    "TYPE_ACCESS_REQUEST",
    "TYPE_ACCESS_GRANT",
    "TYPE_ACCESS_POLICY",
    "Action",
    "ActivityType",
    "Operand",
    "Operator",
    "PUBLIC_AGENT",
    "PREFER_SET_LINKSET",
    "PREFER_LINK_RELATIONS",
    "VERSION",
]
